export const ADD_ADDRESS = "ADD_ADDRESS"
export const ADD_ADDRESS_RESPONSE = "ADD_ADDRESS_RESPONSE"
export const ADD_ADDRESS_FAILED = "ADD_ADDRESS_FAILED"

export const EETCH_ADDRESS = "EETCH_ADDRESS"
export const ADDRESS_LIST_RESPONSE = "ADDRESS_LIST_RESPONSE"
export const ADDRESS_LIST_FAILED = "ADDRESS_LIST_FAILED"

export const UPDATE_ADDRESS = "UPDATE_ADDRESS"
export const ADDRESS_UPDATE_RESPONSE = "ADDRESS_UPDATE_RESPONSE"
export const ADDRESS_UPDATE_FAILED = "ADDRESS_UPDATE_FAILED"

export const REMOVE_ADDRESS = "REMOVE_ADDRESS"
export const ADDRESS_REMOVE_RESPONSE = "ADDRESS_REMOVE_RESPONSE"
export const ADDRESS_REMOVE_FAILED = "ADDRESS_REMOVE_FAILED"

export const SIPPING_ADDRESS = "SIPPING_ADDRESS"

export const SHIPPING_DETAILS = "SHIPPING_DETAILS"
export const LAST_ORDER_ID = "LAST_ORDER_ID"


export const FETCH_COUPON_LIST = "FETCH_COUPON_LIST"
export const COUPON_LIST_RESPONSE = "COUPON_LIST_RESPONSE"
export const COUPON_LIST_FAILED = "COUPON_LIST_FAILED"


export const APPLY_COUPON = "APPLY_COUPON"
export const APPLY_COUPON_RESPONSE = "APPLY_COUPON_RESPONSE"
export const APPLY_COUPON_FAILED = "APPLY_COUPON_FAILED"


export const FETCH_COUNTRY_DATA = "FETCH_COUNTRY_DATA"
export const FETCH_COUNTRY_DATA_RESPONSE = "FETCH_COUNTRY_DATA_RESPONSE"
export const FETCH_COUNTRY_DATA_FAILED = "FETCH_COUNTRY_DATA_FAILED"


export const FETCH_CITY = "FETCH_CITY"
export const FETCH_CITY_RESPONSE = "FETCH_CITY_RESPONSE"
export const FETCH_CITY_FAILED = "FETCH_CITY_FAILED"