export const FETCH_CATEGORIES_DATA = "FETCH_CATEGORIES_DATA";
export const RESPONSE_CATEGORIES_DATA = "RESPONSE_CATEGORIES_DATA";
export const FAILED_CATEGORIES_DATA = "FAILED_CATEGORIES_DATA"


export const FETCH_SUB_CATEGORIES = "FETCH_SUB_CATEGORIES";
export const RESPONSE_SUB_CATEGORIES = "RESPONSE_SUB_CATEGORIES";
export const FAILED_SUB_CATEGORIES = "FAILED_SUB_CATEGORIES"
